CREATE TABLE IF NOT EXISTS fav_asset (
    id SERIAL PRIMARY KEY,
    user_id UUID NOT NULL,
    asset_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);